# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c72e301af3e611a2aa8ec93535a5b9a868512b889a9ca49b6a0d0b2519e47cd7e5106e969791be55cf3e56b0cb5456dec99f0623533926a714f0a32eb28ff9e4

test:
  secret_key_base: 05373acd7ddba18a0202abbb493e0e9055cfb11a75b62804c7f7c6664ee8c26307f7251d6721786251447a1ff805da2d29bd0240d66112d9f9d47cf4249bf823

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
